export default Object.freeze({
  name: "Name",
  age: "Age",
  sex: "Sex",
  questionSymptoms: "Are you experiencing any of the following symptoms?",
  questionDiseaseList: "Have you ever had?",
  questionTravelHistory:
    "Have you travelled anywhere internationally in the last 14 days?",
  questionServiceAmbulance: "Do you need Ambulance Service?",
  questionLookupHospitals: "Are you looking for Hospitals?",
  contactNumber: "Contact Number",
  emailId: "Email id",
  emergencyContactNumber: "Emergency contact Number",
  address: "Address",
  currentLocation: "Current Location",
  buttonSubmit: "Submit",
  buttonReset: "Reset",
  listPatientForm: "Patient form",
  listHospitalReg: "Hospital Registration Form",
  listPatientEnrollment: "Patient enrollment form",
  symptomsCough: "Cough",
  symptomsFever: "Fever",
  symptomsBreathingDifficulty: "Diffuculty in Breathing",
  symptomsNoneOfTheDiseaseList: "None of the Above",
  symptomsHelperText:
    "Would be nice to provide these questions which will help improve better recommendation.",
  hospitalName: "Hospital Name",
  availableServiceAmbulance: "Do you provide Ambulance services?",
  numberOfAmbulance: "Number of Ambulances?",
  availableIsolationWard: "Do you Have Isolation ward?",
  numberIsolationBeds: "Number of Isolation beds for COVID-19",
  numberIcuBeds: "Number of ICU beds for COVID-19",
  numberOxygenUnits: "Number of Oxygen Units",
  numberVentilators: "Number of Ventilators",
  locationHospital: "Hospital Location",
  patientId: "Patient Id",
  enrollmentDate: "Date of Enrollment",
  diseaseDiabetes: "Diabetes",
  diseaseHypertension: "Hypertension",
  diseaseLungDisease: "Lung disease",
  diseaseHeartDisease: "Heart disease",
  lattitude: "Latitude",
  longitude: "Longitude",
});
